# .goreleaser.yml
version: 2

project_name: term-rex

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.BuildDate={{.Date}}
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

brews:
  - name: term-rex
    repository:
      owner: jianongHe
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"  # Add this line
    commit_author:
      name: goreleaserbot
      email: goreleaser@github.com
    homepage: "https://github.com/jianongHe/term-rex"
    description: "A terminal-based dinosaur runner game inspired by Chrome's offline game"
    license: "MIT"
    test: |
      system "#{bin}/term-rex --version"
    install: |
      bin.install "term-rex"

scoops:
  - name: term-rex
    repository:
      owner: jianongHe
      name: scoop-bucket
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"  # Add this line
    homepage: "https://github.com/jianongHe/term-rex"
    description: "A terminal-based dinosaur runner game inspired by Chrome's offline game"
    license: MIT
